Fix issues with undefined signals before reset in psi_common_pl_stage…
paulscherrerinstitute/psi_common pull request #33
Opened 2021-08-12 09:49 UTC by abuerkler

Hi

I fixed two issues with undefined signals which caused issues with the axi stream protocol checker in vunit:

- in psi_common_pl_stage.vhd the two registers DataMain and DataShad were not initialized or set during reset which result that the output is undefined until the first clock cycle
- in psi_common_sync_fifo.vhd the OutVld signal is active before reset because r.RdLevel is undefined

2021-08-13 09:31 UTC, BenoitStef commented
Hi abuerkler,

May I ask you what is your intention to add reset to registers that are clock enabled? 
1. This doesn't help synthesizer to close timing, if not required. apparently you had issue on simulation only, perhaps you should 
    pay attention after the clock is released what is the output of Pl stage.

2. We intensively use the sync fifo in our designs and didn't encounter any issues after synthesis on the fpga. Overmore when the reset is high active the r.RedLvel is assigned to 0. Probably the errors you see are only at the start up of your simulation.

2021-08-13 11:49 UTC, abuerkler commented
Hi BenoitStef 

I understand that you don't like to reset the registers. I did a workaround in my testbench to satisfy the AXI stream protocol checker. However the modification in the sync FIFO doesn't change anything for the synthesis. The problem is only in simulation that the output valid signal is active before reset is applied:
```
if unsigned(r.RdLevel) = 0 then
      OutVld <= '0';
      Empty  <= '1';
    else
      OutVld <= '1';
      Empty  <= '0';
    end if;
```
if RdLevel is undefined, then OutVld is active which is not nice. Applying my change there should not hurt.

2021-08-16 12:36 UTC, BenoitStef requested changes

2021-08-16 12:59 UTC, abuerkler commented on hdl/psi_common_sync_fifo.vhd
> +    if unsigned(r.RdLevel) > 0 then
Previous, it was like following:
```
if unsigned(r.RdLevel) = 0 then
    ...
else
    OutVld <= '1';
end if;
```
I propose to change it to
```
if unsigned(r.RdLevel) > 0 then
    OutVld <= '1';
else
    ....
end if;
```
That ensures that OutVld is '0' before reset was applied.

2021-08-17 14:17 UTC, BenoitStef commented on hdl/psi_common_sync_fifo.vhd
> +    if unsigned(r.RdLevel) > 0 then
Ok let's do for that one, sorry for late reply

2021-08-17 14:18 UTC, BenoitStef requested changes

2021-08-17 14:18 UTC, BenoitStef commented on hdl/psi_common_pl_stage.vhd
> +          r.DataMain <= (others => '0');
please remove this

2021-08-17 14:18 UTC, BenoitStef commented on hdl/psi_common_pl_stage.vhd
> +          r.DataShad <= (others => '0');
please remove this

2021-08-17 14:56 UTC, merged